### ISSUE TITLE
Add Module connection strings in Jenkins

### ISSUE THREAD

**Issue by CIPop** [Azure-Samples/azure-iot-samples-csharp#10]
The module sample requires the IOTHUB_MODULE_CONN_STRING environment variable.
This item is tracking the addition of this variable to our internal Jenkins config and enabling CI execution of the module samples.

**Comment by CIPop** [comment]
We need to update https://github.com/Azure/azure-iot-sdk-csharp/tree/master/e2e/test/prerequisites with the new environment variable.

**Comment by jenoola** [comment]
PR https://github.com/Azure/azure-iot-sdk-csharp/pull/572

**Comment by abhipsaMisra** [comment]
This has been taken care of, closing this issue.
