### ISSUE TITLE
Quickstart device quick stream proxy is not working 

### ISSUE THREAD

**Issue by richardtans** [Azure-Samples/azure-iot-samples-csharp#170]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> cannot compile and build project in the quickstart
ServiceLocalProxyStreamingSample

### Any log messages given by the failure
>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DeviceStreamRequest' could not be found (are you missing a using directive or an assembly reference?)	ServiceLocalProxyStreamingSample	C:\Users\Richard Lawidjaja\Desktop\1\azure-iot-samples-csharp-master\iot-hub\Quickstarts\device-streams-proxy\service\DeviceStreamSample.cs	54	Active

### Expected/desired behavior
>should be able to compiled

### OS and Version? win 10
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by azabbasi** [comment]
Thank you for bringing this up to our attention.
