### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by johnstaveley** [Azure-Samples/azure-iot-samples-csharp#176]
The code is not easy to use at the moment.

Please provide full readmes which describe each section starting here https://github.com/Azure-Samples/azure-iot-samples-csharp so I can see what each part of the repository does without having to pick through the code.

**Comment by vinagesh** [comment]
Thank you for the feedback. We will add appropriate readmes.

**Comment by xtianus79** [comment]
It's broken it doesn't work. How do you get a connection string. Also, the relation to iothub is very abstracted here.

**Comment by vinagesh** [comment]
Can you give specifics on which sample is broken for you and in which sample's context are you finding the IoT hub abstracted? That would help us improve the documentation as well as point you in the right direction.

**Comment by johnstaveley** [comment]
In this page: document what each of the folders contains, maybe provisioning/samples is obvious but horizontal-arm? 
then for instance here: https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/iot-hub/Samples/service
describe what each of the samples does
