### ISSUE TITLE
c# DPS X.509 Edge device sample for individual enrollment

### ISSUE THREAD

**Issue by conekeo** [Azure-Samples/azure-iot-samples-csharp#19]
> Please provide us with the following information:
> ---------------------------------------------------------------
Hi,
I followed this sample for individual enrollment ( powershell .\GenerateTestCertificate.ps1 'certificate.cer' + 'certificate.pfx' generated and it work perfectly by creating a device in Iot hub!), but I didn't find DPS X.509 EDGE device auto-provisioning sample. 

https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-csharp

I follow this to create my edge certificate:
https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md

`New-CACertsCertChain rsa`
`New-CACertsEdgeDevice edgedevice`
`Write-CACertsCertificatesForEdgeDevice edgedevice`

Added the generated file ./certs/new-edge-device.cert.pem in Azure Management Enrollment>Individual Enrollments (is the right file to use????)

When I run it I get this error by using the generated edgedevice.pfx

`Unhandled Exception: Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: AMQP transport exception ---> Microsoft.Azure.Amqp.AmqpException: {"errorCode":401002,"trackingId":"a91b2f04d09c48fa85676d7a7723c292-G:0-TimeStamp:09/14/2018 12:50:42","message":"IotHubUnauthorizedAccess","timestampUtc":"2018-09-14T12:50:42.7172995Z"}`

 Any idea how to auto-provision a edge device with x509 certificate?

**Comment by conekeo** [comment]
closed ticket

**Comment by yzhong94** [comment]
@conekeo sorry about the delay on answering this question.  The reason why you encountered this error is that provisioning Edge devices with X.509 using DPS is not a support scenario at the moment.  We only support provisioning through TPM.
