### ISSUE TITLE
Documentation and samples for AddConfigurationAsync

### ISSUE THREAD

**Issue by elvinm** [Azure-Samples/azure-iot-samples-csharp#23]
Copying over from https://github.com/Azure/azure-iot-sdk-csharp/issues/649.

- **OS, version, SKU and CPU architecture used:** Windows 10 x64 
- **Application's .NET Target Framework :** .Net core 2.0 
- **Device:** Laptop 
- **SDK version used:** Microsoft.Azure.Devices/1.17.0 

## Description of the issue:

Not enough details are provided for calling AddConfigurationAsync in regards to expected exceptions to catch. Details should be provided about failures in cases such as using the same configuration id, or an invalid target condition.

## Code sample exhibiting the issue:

[Samples](https://github.com/Azure/azure-iot-sdk-csharp/blob/c93b167058708aead0d2849972c21dabf815b945/iothub/service/samples/ADMSample/ADMSample.cs#L55)

**Comment by sushilraje** [comment]
Any updates on this?

**Comment by jenoola** [comment]
We have all custom exceptions for Microsoft.Azure.Devices.Client [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/iothub/device/src/Common/Exceptions) and for Microsoft.Azure.Devices [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/iothub/service/src/Common/Exceptions). In both cases, the base exception is called IotHubException, so you may catch that and check error message for details and, if needed, catch for specific exceptions.
