### ISSUE TITLE
Tutorials\Routing\SimulatedDevice-DeviceAuthenticationWithRegistrySymmetricKey Pops up exception

### ISSUE THREAD

**Issue by JadeCoding** [Azure-Samples/azure-iot-samples-csharp#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Download the repo, build and run the sample (environment: VS 2017 enterprise)
>(No matter change the s_deviceKey or not, same exception.)

### Any log messages given by the failure
>System.ArgumentException
  HResult=0x80070057
  Message=Key must be base64 encoded
  Source=Microsoft.Azure.Devices.Client
  StackTrace:
   at Microsoft.Azure.Devices.Client.DeviceAuthenticationWithRegistrySymmetricKey.SetKeyFromBase64String(String key)
   at SimulatedDevice.Program.Main(String[] args) in C:\IoT\azure-iot-samples-csharp-master\azure-iot-samples-csharp-master\iot-hub\Tutorials\Routing\SimulatedDevice\Program.cs:line 23

### Expected/desired behavior
>the string is pretty straightforward, copied from IoT Hub portal. And actually no matter what the string is, all the same error.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10 17763.
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yzhong94** [comment]
@dominicbetts  can you take a look at this error for the routing tutorial?

**Comment by dominicbetts** [comment]
@robinsh - can I pass this one over to you? Thanks.

**Comment by robinsh** [comment]
yes @dominicbetts I'll take a look at it.

**Comment by interfacemirror** [comment]
@robinsh  is there any update on this?

**Comment by robinsh** [comment]
Sure, I’ll take a look.
Robin
