### ISSUE TITLE
Case sensitive path causes build failures in Linux/Mac

### ISSUE THREAD

**Issue by shkreza** [Azure-Samples/azure-iot-samples-csharp#29]
In [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/4cd38b48f08aeda657c67e2e59ec6e2c71f2353d/iot-hub/Quickstarts/device-streams-proxy/service/ServiceLocalProxyStreamingSample.csproj#L9), the project is referencing `..\..\Common\DeviceStreamingCommon.cs`. But the actual directory name is `common` (lower case). This doesn't work in Linux/Mac where filenames are case sensitive.

Same story [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/4cd38b48f08aeda657c67e2e59ec6e2c71f2353d/iot-hub/Quickstarts/device-streams-proxy/device/DeviceLocalProxyStreamingSample.csproj#L9), [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/4cd38b48f08aeda657c67e2e59ec6e2c71f2353d/iot-hub/Quickstarts/device-streams-echo/device/DeviceClientStreamingSample.csproj#L9) and [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/4cd38b48f08aeda657c67e2e59ec6e2c71f2353d/iot-hub/Quickstarts/device-streams-echo/service/ServiceClientStreamingSample.csproj#L9).

**Comment by shkreza** [comment]
@ewertons as FYI

**Comment by rezasherafat** [comment]
Fix is checked in - we can close this issue. @ewertons
