### ISSUE TITLE
Problem while sending event with deviceclient

### ISSUE THREAD

**Issue by phanindra466** [Azure-Samples/azure-iot-samples-csharp#32]
Hi,
    The deviceclient `s_deviceClient.SendEventAsync(message);` giving `CONNECT failed: RefusedNotAuthorized ` exception while sending event from SendEventAsync() method in Microsoft.Azure.Devices.Client DeviceClient  class.The Sample code works fine in console Application 
**Sample Code Method**

  **private static async void SendMessages(string deviceID, string ReadingType, string Readingvalue)
        {
            Debug.WriteLine(deviceID + " " + ReadingType + " " + Readingvalue);
            try
            {
                string s_connectionString = "<Connection String>''
                s_deviceClient = DeviceClient.CreateFromConnectionString(s_connectionString, TransportType.Mqtt);
                // Initial telemetry values

                // Create JSON message
                var telemetryDataPoint = new
                {
                    EventType = ReadingType,
                    EventValue = Readingvalue,
                    EventOccurTime = DateTime.Now.ToString()

                };
                var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
                var message = new Message(Encoding.ASCII.GetBytes(messageString));

                await s_deviceClient.OpenAsync();
                await s_deviceClient.SendEventAsync(message);
                Debug.WriteLine("Message ended");
                await s_deviceClient.CloseAsync();
                //Console.WriteLine("{0} > Sending message: {1}", DateTime.Now, messageString);

            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }**

**exceptions**
`Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in Microsoft.Azure.Devices.Client.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.IotHubClientException' in Microsoft.Azure.Devices.Client.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.IotHubClientException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
The thread 0xe64 has exited with code 0 (0x0).
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.IotHubClientException' in Microsoft.Azure.Devices.Client.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.IotHubClientException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in Microsoft.Azure.Devices.Client.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in Microsoft.Azure.Devices.Client.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException' in System.Private.CoreLib.dll
CONNECT failed: RefusedNotAuthorized`

Giving Error While OpenAsync Method

**Comment by yzhong94** [comment]
@phanindra466 This looks like a problem with your connection string.  You said it worked fine with a console app?  So when do you receive this error?
