### ISSUE TITLE
Is it possible to have multiple device streams in parallel?

### ISSUE THREAD

**Issue by ewertons** [Azure-Samples/azure-iot-samples-csharp#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
- [x] question
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
(On behalf of @HariharanAnantharaman)

This is regarding the Device Streaming proxy example in Quickstarts.

Would it be possible to stream two different processes from device?

For example can I stream SSH and other process at the same time (e.g VNC)? In our scenario, we would need to support remote desktop viewing along with intergated file transfer.
The web wrappers require SFTP server to be running in the end device and it enables remote desktop viewing and file transfer in a single window. 
Currently I need to open up both SSH and VNC ports to achieve this. I would like to know if this would be possible with device streaming. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ewertons** [comment]
Yes, you can have several device streams running in parallel between the same pair of service and device clients.
Some changes might be needed to tailor the code in the samples to route your streaming requests to different applications.

Currently, as you can inspect in the [sample](https://github.com/Azure-Samples/azure-iot-samples-csharp/blob/master/iot-hub/Quickstarts/device-streams-proxy/device/DeviceStreamSample.cs#L19), it is shown how to connect one streaming request to one application endpoint (either SSH, RDP, etc).

To have multiple streaming requests received by a Azure IoT device client and route them to different applications, the logic would need to be changed to:
1. Differentiate the target application between the streaming requests (for example, one request could be sent with a Stream Name "ConnectToSSH" and another to "ConnectToVNC";
2. The user application would then establish a different socket connection (NetworkStream) to the appropriate target application endpoint (either SSH or VNC) based on the name of the Device Streaming request as above.

Makes sense?

**Comment by HariharanAnantharaman** [comment]
Thank you. Will test multiple streaming processes from the device and consuming them by services.
