### ISSUE TITLE
"Unauthorized" error connecting device to DPS with Enrollment Group

### ISSUE THREAD

**Issue by michael-chi** [Azure-Samples/azure-iot-samples-csharp#69]
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
-   Create Certificates

Follow [this](https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md) instruction to create required certificates. Below are all my steps

```bash
chmod 700 certGen.sh

# Create Root and Intermediate CA
./certGen.sh create_root_and_intermediate

# Upload Root CA to IoT DPS
az iot dps certificate create --dps-name michi-dps-20190723 --resource-group michi-dps-rg --name dps20190725root --path ./certs/azure-iot-test-only.root.ca.cert.pem

# Get ETAG
az iot dps certificate list --dps-name michi-dps-20190723 -g michi-dps-rg

# Generate Validation Code for Root CA
az iot dps certificate generate-verification-code -g michi-dps-rg --dps-name michi-dps-20190723 -n dps20190725root -e AAAAAAD6w0Y=

# Generate validation CA for Root CA
./certGen.sh create_verification_certificate <VALIDATION_CODE>

# Get latest ETAG again
az iot dps certificate list --dps-name michi-dps-20190723 -g michi-dps-rg

# Verify Root CA
az iot dps certificate verify --dps-name michi-dps-20190723 -g michi-dps-rg --name dps20190725root --path ./certs/verification-code.cert.pem -e AAAAAAD7qnQ==

# Verify was successful, this can be confirmed via portal as well.
```

-   Once verified, generate device certificate

```bash
# Create Device CA
rm ./certs/new-device.cert.pem
./certGen.sh create_device_certificate deviceid001
```

-   Create Enrollment Group via Portal

I use portal to create an Enrollment Group and choose the root certificate I uploaded. with "CA Certificate" as Certificate Type.

-   I download X509Sample code from [here](https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/provisioning/Samples/device/X509Sample)

-   Copy generated new-device.cert.pfx to project folder then

-   Modify Program.cs to read my pfx file

```csharp
private static string s_certificateFileName = "new-device.cert.pfx";
```

-   According to project readme.md, I change my codes as below

```csharp
#if false
    X509Certificate2 certificate = LoadProvisioningCertificate();
    using (var security = new SecurityProviderX509Certificate(certificate))
#else
    var myCertificate = new X509Certificate2(s_certificateFileName, "1234");
    var myChain = new X509Certificate2Collection();
    
    // Comment out the below line if you do not have a .p7b file (e.g. if you generated certificates using the tool below)
    //myChain.Import("myChain.p7b");
    
    using (var security = new SecurityProviderX509Certificate(myCertificate, myChain))
#endif
```

-   Compile and Run will result in "Unauthorized" error

```shell
dotnet restore
dotnet build
dotnet run
```

### Any log messages given by the failure
>

```shell
RegistrationID = deviceid001
ProvisioningClient RegisterAsync . . .
Unhandled Exception: Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException: {"errorCode":401002,"trackingId":"4fdd0060-3b0a-42e7-9066-5badf3bef16c","message":"Unauthorized","timestampUtc":"2019-07-25T09:15:03.0636061Z"}
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.ValidateOutcome(Outcome outcome)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterDeviceAsync(AmqpClientConnection client, String correlationId, DeviceRegistration deviceRegistration)
   at Microsoft.Azure.Devices.Provisioning.Client.Transport.ProvisioningTransportHandlerAmqp.RegisterAsync(ProvisioningTransportRegisterMessage message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.ProvisioningDeviceClientSample.RunSampleAsync() in /home/azureuser/dps/x509sample/Common/ProvisioningDeviceClientSample.cs:line 31
   at Microsoft.Azure.Devices.Provisioning.Client.Samples.Program.Main(String[] args) in /home/azureuser/dps/x509sample/Program.cs:line 82
```

### Expected/desired behavior
Should successfully provisioned

### OS and Version?
-   OS, version, SKU and CPU architecture used: Ubuntu 18.04
-   Application's .NET Target Framework : netcoreapp2.2
-   Device: Desktop
-   SDK version used:
        Microsoft.Azure.Devices.Client - 1.20.3
        Microsoft.Azure.Devices.Provisioning.Client - 1.4.0
        Microsoft.Azure.Devices.Provisioning.Transport.Amqp - 1.1.9

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mattias-kindborg-axis-communications** [comment]
@michael-chi did you find a solution to your issue? I'm experiencing the same problem.

**Comment by mattias-kindborg-axis-communications** [comment]
I found a solution to the issue.

First, the pfx file does not include the certificate chain. You will have to generate a new certificate using the following command:

```
openssl pkcs12 -export -out new-device.full-chain.pfx -inkey ../private/new-device.key.pem -in new-device.cert.pem -certfile new-device-full-chain.cert.pem
```

The certificate named `new-device.full-chain.pfx` is the one you should reference by the sample code.

There is yet another change you will have to make. In the method `LoadProvisioningCertificate` you will have to return the chain of type `X509Certificate2Collection`, but not the one created from the imported certificate, but instead a new chain that only contain the certificates without private keys. This chain is then injected into `SecurityProviderX509Certificate` in the `main` method.

After this, everything works as expected :fireworks: 

Good luck!
