### ISSUE TITLE
Resources for programmatic device enrollment in C# using DPS for Symmetric Key

### ISSUE THREAD

**Issue by PingPongSet** [Azure-Samples/azure-iot-samples-csharp#70]
I am looking for resources including code examples in C# backend and documentation for programmatic device enrollment using Device Provisioning Service for Symmetric Key.

Specifically, I need to enrol device programmatically in C# at backend via DPS for Symmetric Key.

**Comment by amloh16** [comment]
I am looking for the same as well. -> specifically for group enrollment
